services:
  document-service:
    extends:
      file: docker-compose.base.yml
      service: document-service
    build:
      context: "."
      dockerfile: "./Dockerfile.dev"
    restart: "always"
    volumes:
      - ".:/app"
      - "/app/.venv"
