"""move_document_text_to_r2_urls

Revision ID: 4675d3821fd6
Revises: 97a9fddff7bc
Create Date: 2026-04-08 07:28:03.003137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4675d3821fd6'
down_revision: Union[str, Sequence[str], None] = '97a9fddff7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parsed_content_url', sa.String(length=1024), nullable=True))
    op.add_column('documents', sa.Column('summary_url', sa.String(length=1024), nullable=True))
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'summary_url')
    op.drop_column('documents', 'parsed_content_url')
    # ### end Alembic commands ###
