"""Boolean

Revision ID: c73d83552e17
Revises: 4675d3821fd6
Create Date: 2026-04-08 09:22:02.065677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73d83552e17'
down_revision: Union[str, Sequence[str], None] = '4675d3821fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('has_file', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('documents', sa.Column('has_content', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('documents', sa.Column('has_summary', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('documents', 'parsed_content_url')
    op.drop_column('documents', 'file_url')
    op.drop_column('documents', 'summary_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('parsed_content_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('documents', 'has_summary')
    op.drop_column('documents', 'has_content')
    op.drop_column('documents', 'has_file')
    # ### end Alembic commands ###
